export interface aid {
  '@id'?: string;
  name: string;
  description?: string;
  status?: string;
  origin_url?: string;
  aid_audiences?: string[];
  aid_types?: string[];
  aid_destinations?: string[];
  date_start?: Date;
  date_predeposit?: Date;
  date_submission_deadline?: Date;
  contact_email?: string;
  contact_phone?: string;
  contact_detail?: string;
  time_create?: Date;
  author?: any;
  aid_steps?: string[];
  eligibility?: string;
  aid_recurrence?: string;
  perimeter?: string;
  application_url?: string;
  time_update?: Date;
  slug?: string;
  is_imported?: boolean;
  import_uniqueid?: string;
  financer_suggestion?: string;
  import_data_url?: string;
  date_import_last_access?: Date;
  import_share_licence?: string;
  is_call_for_project?: boolean;
  amended_aid?: string;
  aids_amended?: string[];
  is_amendment?: boolean;
  amendment_author_name?: string;
  amendment_comment?: string;
  amendment_author_email?: string;
  amendment_author_org?: string;
  subvention_rate_min?: number;
  subvention_rate_max?: number;
  subvention_comment?: string;
  contact?: string;
  instructor_suggestion?: string;
  project_examples?: string;
  perimeter_suggestion?: string;
  short_title?: string;
  in_france_relance?: boolean;
  generic_aid?: string;
  aids_from_generic?: string[];
  local_characteristics?: string;
  import_data_source?: any;
  eligibility_test?: any;
  is_generic?: boolean;
  import_raw_object?: string;
  loan_amount?: number;
  other_financial_aid_comment?: string;
  recoverable_advance_amount?: number;
  name_initial?: string;
  author_notification?: boolean;
  import_raw_object_calendar?: string;
  import_raw_object_temp?: string;
  import_raw_object_temp_calendar?: string;
  european_aid?: string;
  import_data_mention?: string;
  has_broken_link?: boolean;
  is_charged?: boolean;
  import_updated?: boolean;
  ds_id?: number;
  ds_mapping?: string;
  ds_schema_exists?: boolean;
  contact_info_updated?: boolean;
  date_create?: Date;
  time_published?: Date;
  date_published?: Date;
  categories?: string[];
  keywords?: any;
  programs?: string[];
  aid_financers?: any;
  aid_instructors?: any;
  project_validateds?: any;
  aid_projects?: any;
  aid_suggested_aid_projects?: any;
  bundles?: any;
  excluded_search_pages?: any;
  highlighted_search_pages?: any;
  log_aid_views?: any;
  log_aid_application_url_clicks?: any;
  log_aid_origin_url_clicks?: any;
  log_aid_contact_clicks?: any;
  log_aid_createds_folders?: any;
  log_aid_eligibility_tests?: any;
  nb_views?: number;
  score_total?: number;
  score_objects?: number;
  url?: string;
  financers?: string[];
  instructors?: string[];
  project_references_suggestions?: string[];
  organization?: any;
  application_url_text?: string;
  origin_url_text?: string;
  keyword_references?: any;
  project_references?: string[];
  date_check_broken_link?: Date;
  aid_locks?: any;
  keyword_reference_suggesteds?: any;
  sanctuarized_fields?: any;
  import_datas?: any;
  live?: boolean;
  project_reference_missings?: any;
  last_editor?: any;
  readonly id?: number;
  readonly project_references_searched?: string[];
  readonly aids_from_generic_live?: string[];
  readonly approaching_deadline?: boolean;
  readonly days_before_deadline?: number;
  readonly financial?: boolean;
  readonly technical?: boolean;
  readonly grant?: boolean;
  readonly loan?: boolean;
  readonly on_going?: boolean;
  readonly recurring?: boolean;
  readonly draft?: boolean;
  readonly published?: boolean;
  readonly local?: boolean;
  readonly calendar?: boolean;
  readonly coming_soon?: boolean;
  readonly expired?: boolean;
  readonly financers_public_or_corporate?: string;
}
