#!/bin/sh
if sh -c ': >/dev/tty' >/dev/null 2>/dev/null; then
    exec </dev/tty; yarn node-talisman --githook pre-commit -i;
    npx lint-staged
else
    yarn node-talisman --githook pre-commit;
    npx lint-staged
fi
